# Applying quantum cognition to address disjunction effect

### _Here I look at a few studies in which quantum cognition explains disjunction paradoxes_

In [39]:
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import zipfile
from pathlib import Path


## Insert Given Values from Study:

In [40]:
# Croson numbers
"""
PBd = 0.54
PAd = 0.225

#notice this is just a game theory matrix so must sum across row
PAd_Bd = 0.68
PAd_Bc = 0.17
PAc_Bc = 0.83
PAc_Bd = 0.32
"""

'\nPBd = 0.54\nPAd = 0.225\n\n#notice this is just a game theory matrix so must sum across row\nPAd_Bd = 0.68\nPAd_Bc = 0.17\nPAc_Bc = 0.83\nPAc_Bd = 0.32\n'

In [53]:

# Kahneman and Tversky numbers
PBd = 0.5
PAd = 0.36

#notice this is just a game theory matrix so must sum across row
PAd_Bd = 0.69
PAd_Bc = 0.59
PAc_Bc = 0.41
PAc_Bd = 0.31


In [54]:

# Exam & Hawaii experiment numbers

#PBd = 0.5
#PAd = 0.32

#notice this is just a game theory matrix so must sum across row
#PAd_Bd = 0.54
#PAd_Bc = 0.57
#PAc_Bc = 0.43
#PAc_Bd = 0.46

In [43]:
# Read & Van Leeuwen

PBd = 0.5 # probability hungry or not CHECK THIS!
# PAd = 0.32 # probability unhealthy snack 

#notice this is just a game theory matrix so must sum across row
PAd_Bd = .78
PAd_Bc = .56
PAc_Bc = .44
PAc_Bd = (1 - .78)

PAd = .9

## Here's the game theory matrix:

In [55]:
gt_matrix = np.array([[PAc_Bc, PAd_Bc], 
                      [PAc_Bd, PAd_Bd]])
gt_matrix

array([[ 0.41,  0.59],
       [ 0.31,  0.69]])

## Calculate P_t(A1)

In [56]:
P_tA1 =  PBd*PAd_Bd + (1 - PBd) * PAd_Bc
P_tA1

0.6399999999999999

## Now calculate δ (interference) term

In [98]:
d1 = PAd - P_tA1
d2 = -d1
d1, d2

(-0.2799999999999999, 0.2799999999999999)

In [93]:
#=ACOS(B14/(2*SQRT(B4*B3*B5*0.46)))
theta_d1 = np.arccos(d1/(2*np.sqrt(PAd_Bd*PBd*PAd_Bc*(1-PBd))))
theta_d2 = np.arccos(d2/(2*np.sqrt(PAc_Bd*PBd*PAc_Bc*(1-PBd))))
theta_d1, theta_d2

(1.2020173476537055, 2.2720049473427109)

## V Matrix:


In [94]:
V = np.array([[np.sqrt(PAd_Bd), np.sqrt(PAd_Bc) + np.exp(np.complex(0, theta_d1))],
             [np.sqrt(PAc_Bd) + np.exp(np.complex(0, theta_d2)), PAc_Bc]])
V

array([[ 0.83066239+0.j        ,  1.12859135+0.93276819j],
       [-0.08836518+0.76406301j,  0.41000000+0.j        ]])

## set  (Bd|s), (Bc|s)

In [95]:
Bd_S = np.sqrt(PBd)
Bc_S = np.sqrt(1 - PBd)
Bd_S, Bc_S

(0.70710678118654757, 0.70710678118654757)

## Calculate Psi

In [96]:
AdS = np.sqrt(PAd_Bd*PBd) + np.sqrt(PAd_Bc*(1-PBd)) * np.exp(complex(0, theta_d1))
AcS =  np.sqrt(PAc_Bd*PBd) * np.exp(complex(0, theta_d2)) + np.sqrt(PAc_Bc*(1-PBd))
AdS,  AcS

((0.78315600829804877+0.50662280511902202j),
 (0.1987767469347238+0.30081190946843978j))

## Take conjugate, multiply to get result

In [97]:
AdS_squared = np.conj(AdS) * AdS
AcS_squared = np.conj(AcS) * AcS
np.real(AdS_squared), np.real(AcS_squared)


(array(0.8699999999999999), array(0.13000000000000003))

Some psudonotes on applying to projection bias:
(paper: https://www.sciencedirect.com/science/article/pii/S0749597898928035)



In [77]:
# Read & Van Leeuwen

PAplus_C = 0.5
PAminus_C = 1-PAplus_C
PBplus = .9
PBminus = .1
# PAd = 0.32 # probability unhealthy snack 

#notice this is just a game theory matrix so must sum across row
Ppp = .78
Ppm = .56
Pmp = .22
Pmm = .44

In [78]:
gt_matrix = np.array([[Ppp, Ppm], 
                      [Pmp, Pmm]])
gt_matrix

array([[ 0.78,  0.56],
       [ 0.22,  0.44]])

In [82]:
dplus = PBplus - PAplus_C * Ppp - PAminus_C * Ppm
dplus

0.22999999999999998

In [83]:
dminus = PBminus - PAplus_C * Pmp - PAminus_C * Pmm
dminus

-0.22999999999999998

In [84]:
Pip = PAplus_C * PAminus_C * Ppp*Ppm
Pip

0.10920000000000002

In [85]:
Pim = PAplus_C * PAminus_C * Pmp * Pmm
Pim

0.0242

In [87]:
Lp = dplus / (2*np.sqrt(Pip))
Lp

0.34800583128456136

In [88]:
Lm = dminus / (2 * np.sqrt(Pim))
Lm

-0.73924799851320866

In [90]:
Tp = np.arccos(Lp)
Tp

1.2153531958338908

In [91]:
Tm = np.arccos(Lm)
Tm

2.4027493315370041